default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: "ubuntu"
      password: "password"

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production